name: Hello World Workflow
on: push
branches: main
jobs:
 build:
 runs-on: ubuntu-latest
 steps:
    - name: Say Hello
 uses: actions/checkout@v3
    - name: Print greeting
 run: echo "ðŸ‘‹ Hello, GitHub Actions !"
